const { chromium } = require("../lib/browser.cjs");
const URL = "http://localhost:8080/"; let pass = 0, fail = 0;
const ok = (n, c, x = "") => { c ? pass++ : fail++; console.log(c ? "PASS" : "FAIL", n, c ? "" : x); };
(async () => {
  const b = await chromium.launch({ });
  const mk = async (name, room) => { const p = await (await b.newContext({ viewport: { width: 1200, height: 800 }, acceptDownloads: true })).newPage(); p.errs = []; p.on("pageerror", (e) => p.errs.push(e.message)); p.on("dialog", (d) => d.accept()); await p.goto(room || URL); await p.locator("input").first().fill(name); await p.getByRole("button", { name: room ? /join/i : /create/i }).first().click(); await p.locator(".composer textarea").waitFor(); return p; };
  const a = await mk("Alice <b>é😀</b>"); const room = a.url(); const bob = await mk("Bob", room);
  await a.getByText(/Bob joined/).waitFor({ timeout: 20000 });
  const say = async (p, t) => { await p.locator(".composer textarea").fill(t); await p.keyboard.press("Enter"); };
  await say(bob, '<img src=x onerror="window.__pwned=1"><script>window.__pwned=1</script> & "quotes"');
  await say(bob, "```js\nconst a = 1 < 2 && 3 > 2;\n```");
  await say(a, "multi\nline  spaced   text");
  await a.locator('.composer input[type=file]').setInputFiles(["dl/pic.png", "dl/..notes <b>evil:name?.txt"]);
  await bob.waitForTimeout(3500);
  const dlg = async (p, withFiles) => { await p.getByRole("button", { name: "Export", exact: true }).click(); await p.getByRole("dialog").waitFor(); if (withFiles) await p.getByLabel(/Include the/).check(); const [d] = await Promise.all([p.waitForEvent("download"), p.getByRole("dialog").getByRole("button", { name: "Export", exact: true }).click()]); return d; };
  const d1 = await dlg(a, true); await d1.saveAs("dl/alice.zip");
  ok("download has a sensible name", /^deca-[a-z0-9]+-\d{4}-\d{2}-\d{2}\.zip$/.test(d1.suggestedFilename()), d1.suggestedFilename());
  ok("dialog closes after export", (await a.getByRole("dialog").count()) === 0);
  ok("a toast confirms", /Saved deca-/.test(await a.locator("body").innerText()));
  const d2 = await dlg(bob, false); await d2.saveAs("dl/bob.zip");
  const dd = await dlg(a, false); await dd.saveAs("dl/alice-nofiles.zip");
  await bob.getByRole("button", { name: "Export", exact: true }).click();
  ok("dialog mentions files held", /file/.test(await bob.getByRole("dialog").innerText()));
  await bob.keyboard.press("Escape"); ok("Esc closes the dialog", (await bob.getByRole("dialog").count()) === 0);
  await a.getByRole("button", { name: "Export", exact: true }).click(); await a.mouse.click(5, 5); ok("backdrop click closes the dialog", (await a.getByRole("dialog").count()) === 0);
  ok("no injected script ran on either page", !(await a.evaluate(() => window.__pwned)) && !(await bob.evaluate(() => window.__pwned)));
  ok("no page errors", a.errs.length + bob.errs.length === 0, a.errs.concat(bob.errs).join("|"));
  await b.close(); console.log(`\n${pass} passed, ${fail} failed`);
})().catch((e) => { console.log("ERR", e.message.split("\n").slice(0, 3).join(" ")); process.exit(1); });
