const http = require("http"), fs = require("fs"), path = require("path");
const { chromium } = require("../lib/browser.cjs");
const DIST = require("node:path").join(__dirname, "..", "..", "dist-static"), PREFIX = "/deca/";
const MIME = { ".html": "text/html", ".js": "text/javascript", ".css": "text/css", ".json": "application/json", ".svg": "image/svg+xml" };
const hits = [];
const srv = http.createServer((q, r) => { hits.push(q.url); if (!q.url.startsWith(PREFIX)) { r.statusCode = 404; return r.end("no"); } let p = q.url.slice(PREFIX.length).split("?")[0] || "index.html"; const f = path.join(DIST, p); if (!f.startsWith(DIST) || !fs.existsSync(f) || fs.statSync(f).isDirectory()) { r.statusCode = 404; return r.end("no"); } r.setHeader("Content-Type", MIME[path.extname(f)] || "application/octet-stream"); fs.createReadStream(f).pipe(r); });
let pass = 0, fail = 0; const ok = (n, c) => { c ? pass++ : fail++; console.log((c ? "ok   " : "FAIL ") + n); };
srv.listen(8099, async () => {
  const b = await chromium.launch({ });
  const p = await (await b.newContext()).newPage();
  const bad = []; p.on("pageerror", (e) => bad.push(e.message));
  await p.goto("http://localhost:8099/deca/");
  await p.locator("input").first().fill("Ann");
  ok("opens straight in no-server mode", await p.getByRole("button", { name: "Create a space (no server)" }).isVisible());
  ok("no toggle back to a server", (await p.getByRole("button", { name: /Use a server instead|No server\? Connect by code/ }).count()) === 0);
  await p.getByRole("button", { name: "Create a space (no server)" }).click();
  await p.locator(".composer textarea").waitFor();
  const invite = await p.evaluate(() => location.href);
  ok("invite keeps the subpath", invite.startsWith("http://localhost:8099/deca/#/m/"));
  await p.waitForTimeout(1500);
  ok("no /ws or /ice or root requests", hits.every((u) => u.startsWith(PREFIX) && !/\/(ws|ice)(\?|$)/.test(u)));
  ok("games.json served from the subpath", hits.includes(PREFIX + "games.json"));
  const gj = await p.evaluate(async () => (await fetch("games.json")).json());
  ok("the bundled free games are listed (snake, platformer; Freedoom only when its data file was fetched)", ["snake", "platformer"].every((id) => gj.some((g) => g.id === id)) && gj.length >= 2);
  const g = await p.evaluate(async () => (await fetch("games/snake/index.html")).status);
  ok("a game file loads", g === 200);
  const p2 = await (await b.newContext()).newPage();
  await p2.goto("http://localhost:8099/deca/#/s/abcdef123456");
  await p2.locator("input").first().fill("Bo");
  ok("server-room link explains itself", await p2.getByText(/needs a server/).isVisible());
  ok("no page errors", bad.length === 0);
  console.log(`\n${pass} passed, ${fail} failed`); await b.close(); srv.close(); process.exit(fail ? 1 : 0);
});
